version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:                            # environment variables
      - POSTGRES_PASSWORD=postgres_password # Postgres requires this envitonment variable
  redis:
    image: 'redis:latest'
  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - '3050:80'
    depends_on:
      - api
      - client
  api:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./server:/app
    depends_on:
      - postgres
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379                     # 6379 is the default port for redis
      - PGUSER=postgres
      - PGHOST=postgres                     # "postgres" is a reference to the other service
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432                         # 5432 is the default port for postgres
  client:
    stdin_open: true
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379                     # 6379 is the default port for redis